# Generated by Django 2.2.1 on 2019-05-04 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taskapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('competency', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('deliverable', models.FileField(upload_to='deliverable/', verbose_name='Deliverable')),
                ('status', models.CharField(choices=[(taskapp.models.TaskStatus('Closed'), 'Closed'), (taskapp.models.TaskStatus('In Progress'), 'In Progress'), (taskapp.models.TaskStatus('Completed'), 'Completed'), (taskapp.models.TaskStatus('Terminated'), 'Terminated')], max_length=20)),
                ('staff_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_pic', to='taskapp.Staff')),
            ],
        ),
    ]
