# Generated by Django 2.2.1 on 2019-05-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0005_historicalproject_historicaltask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='deliverable',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Deliverable'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deliverable',
            field=models.FileField(blank=True, null=True, upload_to='deliverable/', verbose_name='Deliverable'),
        ),
    ]
